name: Manual PR Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Install Helmfile
        run: |
          curl -LO https://github.com/roboll/helmfile/releases/latest/download/helmfile_linux_amd64
          chmod +x helmfile_linux_amd64
          sudo mv helmfile_linux_amd64 /usr/local/bin/helmfile
          helmfile --version

      - name: Deploy PR Environment
        run: |
          echo "Deployment steps go here"
          # You can use your deployment scripts here
